:characters:
  :description: Gets information about characters
  :methods:
    :find_by_name:
      :description: finds chracters based on value given
      :model: character
      :method: name_search
    :most_popular:
      :description: shows the characters with most appearances
      :model: character
      :method: characters_most_appearances
    :most_chatty:
      :description: shows the characters most chatty
      :model: character
      :method: characters_most_talkative
    :list:
      :description: shows the list of characters
      :model: character
      :method: characters_list_x_amount
:episodes:
  :description: Gets information about episodes
  :methods:
    :find_by_name:
      :description: find an episode based on value given
      :model: episode
      :method: name_search
    :most_popular:
      :description: gets a list of episodes based in amount of viewers
      :model: episode
      :method: most_popular
    :season_info:
      :description: shows season information 1 - 28
      :model: episode
      :method: get_season_info
:locations:
  :description: Gets information about locations
  :methods:
    :find_by_name:
      :description: finds locations based on value given
      :model: location
      :method: name_search
:stats:
  :description: Curiosities about The Simpsons
  :methods:
    :show_characters_stats:
      :description: shows the totals for a character
      :model: stat
      :method: show_characters_stats
    :show_episodes_stats:
      :description: shows the totals for an episode
      :model: stat
      :method: show_episodes_stats
    :show_locations_stats:
      :description: shows the totals for a location
      :model: stat
      :method: show_locations_stats
:lines:
  :description: gets information about lines
  :methods:
    :find_by_segment:
      :description: 'find a line by some segment of it (will only return up to 50 matches)'
      :model: line
      :method: find_by_segment
    :find_by_id:
      :description: 'find a line and all its information by database id number'
      :model: line
      :method: find_by_id
    :random:
      :description: 'see a random line from any time in the show'
      :model: line
      :method: random
:help:
  :description: show this menu
:exit:
  :description: exit the program
