:characters:
  :description: Gets information about characters
  :methods:
    :print_first_ten:
      :description: Print first 10
      :model: character
      :method: print_first_ten
:episodes:
  :description: Gets information about episodes
  :methods:
    :find_by:
      :description: 'find an episode by attribute: value'
      :model: episode
      :method: find_by
:locations:
  :description: Gets information about locations
  :methods:
    :find_by:
      :description: 'find a location by attribute: value'
      :model: location
      :method: find_by
:stats:
  :description: Curiosities about The Simpsons
  :methods:
    :get_the_most_popular_location:
      :description: Shows the most popular location
      :model: stat
      :method: get_the_most_popular_location
    :test:
      :description: Test Method
      :model: stat
      :method: test
:lines:
  :description: gets information about lines
  :methods:
    :find_by:
      :description: 'find a line by attribute: value'
      :model: line
      :method: find_by
    :find:
      :description: find information on up to 20 lines of dialogue containing the given string
      :model: line
      :method: find
:help:
  :description: show this menu
:exit:
  :description: exit the program
