:characters:
  :description: Gets information about characters
  :methods:
    :find_by_name:
      :description: finds chracters based on value given
      :model: character
      :method: name_search
    :most_popular:
      :description: shows the characters with most appearances
      :model: character
      :method: characters_most_appearances
    :most_chatty:
      :description: shows the characters most chatty
      :model: character
      :method: characters_most_talkative
    :list:
      :description: shows the list of characters
      :model: character
      :method: characters_list_x_amount
:episodes:
  :description: Gets information about episodes
  :methods:
    :find_by:
      :description: 'find an episode by attribute: value'
      :model: episode
      :method: find_by
:locations:
  :description: Gets information about locations
  :methods:
    :find_by_name:
      :description: finds locations based on value given
      :model: location
      :method: name_search
:stats:
  :description: Curiosities about The Simpsons
  :methods:
    :get_the_most_popular_location:
      :description: Shows the most popular location
      :model: stat
      :method: get_the_most_popular_location
:lines:
  :description: gets information about lines
  :methods:
    :find_by_segment:
      :description: 'find a line by some segment of it'
      :model: line
      :method: find_by_segment
    :find:
      :description: find information on up to 20 lines of dialogue containing the given string
      :model: line
      :method: find
:help:
  :description: show this menu
:exit:
  :description: exit the program
